import { Metadata } from 'next';
import { ReactNode } from 'react';
import { NavigationalMenu } from '@/components/core/shop/common/navbar';
import MarketFooter from '@/components/core/common/footer';

interface Props {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: Props) => {
  return (
    <main className='px-6'>
      <NavigationalMenu />
      {children}
      <MarketFooter />
    </main>
  );
};

export default RootLayout;
