/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as config_http from "../config/http.js";
import type * as core_shop_categories from "../core/shop/categories.js";
import type * as core_shop_index from "../core/shop/index.js";
import type * as core_shop_orders from "../core/shop/orders.js";
import type * as core_shop_products from "../core/shop/products.js";
import type * as core_shop_reviews from "../core/shop/reviews.js";
import type * as core_shop_tags from "../core/shop/tags.js";
import type * as core_storage_file from "../core/storage/file.js";
import type * as core_storage_folder from "../core/storage/folder.js";
import type * as core_users_index from "../core/users/index.js";
import type * as func_doc from "../func/doc.js";
import type * as func_messages from "../func/messages.js";
import type * as func_tasks from "../func/tasks.js";
import type * as schema_index from "../schema/index.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "config/http": typeof config_http;
  "core/shop/categories": typeof core_shop_categories;
  "core/shop/index": typeof core_shop_index;
  "core/shop/orders": typeof core_shop_orders;
  "core/shop/products": typeof core_shop_products;
  "core/shop/reviews": typeof core_shop_reviews;
  "core/shop/tags": typeof core_shop_tags;
  "core/storage/file": typeof core_storage_file;
  "core/storage/folder": typeof core_storage_folder;
  "core/users/index": typeof core_users_index;
  "func/doc": typeof func_doc;
  "func/messages": typeof func_messages;
  "func/tasks": typeof func_tasks;
  "schema/index": typeof schema_index;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
